version: '3.8'

services:
  # Layanan Database untuk MLFlow
  db:
    image: postgres:13
    container_name: mlflow_db
    environment:
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow
      - POSTGRES_DB=mlflow
    ports:
      - "2345:5432"
    volumes:
      - mlflow_db_data:/var/lib/postgresql/data

  # Layanan Object Storage (S3-compatible) untuk Artifacts MLFlow
  minio:
    image: minio/minio
    container_name: mlflow_minio
    ports:
      - "9000:9000"
      - "9001:9001" 
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - mlflow_minio_data:/data

  # MLFlow Tracking Server
  mlflow_server:
    image: python:3.9-slim
    container_name: mlflow_server
    command: >
      bash -c "apt-get update && apt-get install -y git &&
      pip install mlflow boto3 psycopg2-binary &&
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@db:5432/mlflow
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0
      --port 5001"
    ports:
      - "5001:5001"
      # - "8001:8000" # Ray.io
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - db
      - minio

  # Aplikasi FastAPI kita
  fastapi_app:
    build: ./app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5001
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - mlflow_server

volumes:
  mlflow_db_data:
  mlflow_minio_data: