global:
  scrape_interval: 15s # Interval default untuk mengumpulkan metrik

# Daftar target yang akan di-scrape oleh Prometheus
scrape_configs:
- job_name: 'fastapi_app'
  # Konfigurasi ini memungkinkan Prometheus menemukan layanan kita di dalam jaringan Docker
  static_configs:
  - targets: [ 'fastapi_app:8000' ] # 'fastapi_app' adalah nama service di docker-compose, 8000 adalah port internal
